import type { DeviceDefinition, Terminal } from './simulation';
const ground: Terminal = { name: 'GND', type: 'ground' },
  vcc: Terminal = { name: 'VCC', type: 'power', rail: '3V3' },
  ext: Terminal = { name: 'EXT 5V', type: 'power', rail: '5V' };
const pin = (name: string, type: Terminal['type'] = 'out'): Terminal => ({
  name,
  type,
});
const i2c = [vcc, ground, pin('SDA', 'i2c'), pin('SCL', 'i2c')];
const spi = [
  vcc,
  ground,
  pin('MOSI', 'spi'),
  pin('MISO', 'in'),
  pin('SCLK', 'spi'),
  pin('CS', 'out'),
];
const analog = [vcc, ground, pin('OUT', 'adc')];
const uart = [vcc, ground, pin('TX → RX', 'in'), pin('RX ← TX', 'uart')];
const audio = [
  vcc,
  ground,
  pin('BCLK', 'i2s'),
  pin('WS', 'i2s'),
  pin('DIN', 'i2s'),
];
function model(
  id: DeviceDefinition['id'],
  name: string,
  category: string,
  protocol: string,
  terminals: Terminal[],
  description: string,
  memory = 2,
  address?: number,
): DeviceDefinition {
  return {
    id,
    name,
    category,
    subtitle: category + ' experiment',
    protocol,
    terminals,
    description,
    memory,
    address,
    color:
      category === 'Actuators'
        ? '#b88d62'
        : category === 'Audio'
          ? '#778aa7'
          : category === 'Displays'
            ? '#528e83'
            : category === 'Storage'
              ? '#aa8b66'
              : '#6c9f91',
  };
}
export const extraDevices: DeviceDefinition[] = [
  model(
    'rgb',
    'RGB LED / MOSFET strip',
    'Lighting',
    '3-channel PWM',
    [ext, ground, pin('R'), pin('G'), pin('B')],
    'Three independently controlled PWM channels. This teaching breakout includes MOSFET drivers and an external 5 V LED supply. Brightness scales red, green, and blue. A physical high-power strip requires correctly rated drivers and its own supply.',
  ),
  model(
    'neopixel',
    'Addressable LED strip',
    'Lighting',
    'Timed serial',
    [ext, ground, pin('DIN')],
    'A virtual WS2812-style strip with a logic-level shifter, series data resistor, and decoupling. Pixel count and brightness determine the estimated current and RGB buffer size. The scene represents a strip; it does not implement the exact LED timing protocol.',
  ),
  model(
    'relay',
    'Relay + low-voltage load',
    'Actuators',
    'GPIO',
    [ext, ground, pin('IN')],
    'An isolated teaching load controlled by a transistor-driven relay with flyback protection. Active-low mode inverts the GPIO level. The virtual load is low-voltage; this model is not a mains wiring guide.',
  ),
  model(
    'fan',
    'Fan + MOSFET driver',
    'Actuators',
    'PWM',
    [ext, ground, pin('PWM')],
    'A low-voltage fan with an external supply, MOSFET, and flyback protection. Duty cycle and the chosen no-load RPM set the idealized speed. Mechanical inertia, stall current, and fan-specific control protocols are simplified.',
  ),
  model(
    'motor',
    'DC motor + H-bridge',
    'Actuators',
    'PWM + direction',
    [ext, ground, pin('PWM'), pin('DIR')],
    'An H-bridge teaching module controls speed and direction from logic pins. An independent 5 V load supply is modeled. The stall-current setting estimates worst-case supply demand; back-EMF and motor inductance are not solved.',
  ),
  model(
    'stepper',
    'Stepper + STEP/DIR driver',
    'Actuators',
    'STEP / DIR',
    [ext, ground, pin('STEP'), pin('DIR'), pin('ENABLE')],
    'A step/direction driver abstraction with a modeled 5 V motor supply. Steps per revolution and microstep ratio convert commanded pulse frequency to revolutions per minute. It does not imply that a particular A4988 board accepts a 5 V motor supply.',
  ),
  model(
    'bmp280',
    'BMP280 pressure sensor',
    'Environment',
    'I²C',
    i2c,
    'Pressure and temperature teaching model. Unlike BME280, BMP280 does not measure humidity. Address selection, offsets, and oversampling are adjustable. Values are synthetic environmental inputs, not readings from hardware.',
    3,
    0x76,
  ),
  model(
    'sht31',
    'SHT31 humidity sensor',
    'Environment',
    'I²C',
    i2c,
    'Digital temperature/humidity breakout modeled at 3.3 V. Temperature, humidity, offset, and sampling interval can be varied. CRC, heater effects, and condensation are described rather than electrically emulated.',
    3,
    0x44,
  ),
  model(
    'bh1750',
    'BH1750 light sensor',
    'Environment',
    'I²C',
    i2c,
    'A lux sensor teaching model for automatic lighting. Adjust illuminance and measurement interval, then link its value to a light with a threshold rule. The simulated bus address is selectable.',
    2,
    0x23,
  ),
  model(
    'ds18b20',
    'DS18B20 thermometer',
    'Environment',
    '1-Wire',
    [vcc, ground, pin('DQ', 'out')],
    'Externally powered one-wire temperature sensor with a modeled 4.7 kΩ pull-up. This profile uses three-wire power, not parasitic power. Conversion resolution changes modeled conversion time; physical devices also require ROM selection and CRC checking.',
  ),
  model(
    'dht22',
    'DHT22 climate sensor',
    'Environment',
    'Single-wire',
    [vcc, ground, pin('DATA')],
    'A low-rate temperature/humidity teaching breakout with a data pull-up. This single-wire protocol is not Dallas 1-Wire. Sampling faster than the modeled two-second minimum is flagged.',
  ),
  model(
    'co2',
    'SCD4x CO₂ sensor',
    'Environment',
    'I²C',
    i2c,
    'A simplified CO₂, temperature, and humidity sensor model. The concentration is an injected test value, not inferred from an MQ gas resistance. Warm-up, pressure compensation, and automatic calibration matter on a physical sensor.',
    4,
    0x62,
  ),
  model(
    'mq135',
    'MQ135 conditioned analog module',
    'Environment',
    'ADC',
    [ext, ground, pin('OUT', 'adc')],
    'Models an MQ135 module with heater power and an explicit analog divider/conditioning stage limited to 3.3 V. The output is a raw air-quality proxy, not calibrated CO₂ ppm or a certified AQI. Warm-up and gas calibration are not simulated.',
  ),
  model(
    'uv',
    'Conditioned UV sensor',
    'Environment',
    'ADC',
    analog,
    'Analog UV teaching breakout with a 3.3 V-limited output. Input gain and offset calibrate the synthetic voltage used by automation. Without a sensor-specific spectral calibration, this is not a verified UV index.',
  ),
  model(
    'soil',
    'Capacitive soil sensor',
    'Environment',
    'ADC',
    analog,
    'Moisture input maps between dry and wet calibration voltages. Adjust both endpoints to see why different soil, salinity, and probe placement require calibration. The board must receive an ADC-safe signal.',
  ),
  model(
    'ldr',
    'LDR voltage divider',
    'Environment',
    'ADC',
    analog,
    'A light-dependent resistor and fixed resistor form a voltage divider. The light input is normalized rather than a calibrated lux measurement. Fixed resistance changes the modeled divider voltage.',
  ),
  model(
    'pir',
    'PIR motion sensor',
    'Motion',
    'GPIO input',
    [vcc, ground, pin('OUT', 'in')],
    'A 3.3 V-compatible motion-output teaching module. Motion sets a digital output and can trigger a light or relay rule. Detection range, retrigger timing, and warm-up depend on the physical module.',
  ),
  model(
    'ultrasonic',
    'Ultrasonic ranging module',
    'Motion',
    'Trigger / echo',
    [ext, ground, pin('TRIG'), pin('ECHO', 'in')],
    'A rangefinder with a modeled divider on its 5 V ECHO output. Distance and ambient temperature determine ideal echo flight time. The simplified model excludes multipath, blind-zone physics, and timeouts from absorbent targets.',
  ),
  model(
    'imu',
    'BMI270 inertial sensor',
    'Motion',
    'I²C',
    i2c,
    'Six-axis IMU teaching model. Set tilt and acceleration to examine telemetry; use tilt as an automation input. The displayed tilt is a controlled scenario, not a full sensor-fusion algorithm.',
    6,
    0x68,
  ),
  model(
    'encoder',
    'Rotary encoder',
    'Inputs',
    'GPIO interrupt',
    [vcc, ground, pin('A', 'in'), pin('B', 'in'), pin('SW', 'in')],
    'A quadrature encoder with modeled pull-ups. The position and pulses-per-revolution determine the angular reading. Real implementations must decode transition order and handle contact bounce.',
  ),
  model(
    'joystick',
    'Two-axis joystick',
    'Inputs',
    '2 × ADC + button',
    [vcc, ground, pin('X', 'adc'), pin('Y', 'adc'), pin('SW', 'in')],
    'Two potentiometers and a push switch. X/Y controls map to ADC voltages. Dead zone suppresses small center offsets. Each analog axis requires its own ADC-capable input.',
  ),
  model(
    'reed',
    'Reed / door switch',
    'Inputs',
    'GPIO input',
    [ground, pin('SIGNAL', 'in')],
    'A door contact with a modeled external pull-up. Open/closed state can drive an alarm rule. Wiring polarity and the meaning of normally-open/closed should be chosen explicitly.',
  ),
  model(
    'lcd1602',
    '16 × 2 LCD backpack',
    'Displays',
    'I²C',
    i2c,
    'A 3.3 V-safe teaching LCD backpack with virtual level translation. Text capacity, contrast, and backlight are configurable. Many real 5 V LCD backpacks pull I²C up to 5 V; inspect the module before connecting.',
    2,
    0x27,
  ),
  model(
    'epaper',
    'E-paper display',
    'Displays',
    'SPI',
    [...spi.filter((t) => t.name !== 'MISO'), pin('DC'), pin('BUSY', 'in')],
    'A monochrome e-paper teaching display. Width, height, and color depth in the global Parameters tab determine the framebuffer workload. Ghosting, waveform LUTs, and high-voltage panel drive are abstracted.',
    16,
  ),
  model(
    'gt911',
    'GT911 capacitive touch',
    'Displays',
    'I²C',
    [...i2c, pin('RST'), pin('INT', 'in')],
    'A GT911 touch-controller profile with reset and interrupt lines. Set synthetic touch coordinates and contact state within the reference panel. The controller’s address depends on the reset/interrupt sequence; this model exposes its selected address.',
    8,
    0x5d,
  ),
  model(
    'p4panel',
    'CrowPanel P4 MIPI panel',
    'Displays',
    'MIPI-DSI + PWM',
    [ext, ground, pin('BACKLIGHT')],
    'A reference 1024 by 600 RGB565 display. MIPI-DSI uses dedicated board lanes and initialized PHY and panel rails, represented as internal connections here. Only backlight control is routable. This is not a generic SPI display.',
    0,
  ),
  model(
    'uda1334',
    'UDA1334A line-out DAC',
    'Audio',
    'I²S',
    audio,
    'An external I2S line-output path. BCLK, WS/LRCK, and serial audio DIN drive a stereo DAC. Its analog line output needs an appropriate amplifier for a speaker. Sample rate, bit width, and buffering affect throughput and RAM.',
    12,
  ),
  model(
    'max98357',
    'MAX98357A amplifier',
    'Audio',
    'I²S',
    [ext, ground, pin('BCLK', 'i2s'), pin('WS', 'i2s'), pin('DIN', 'i2s')],
    'A digital I²S class-D speaker amplifier. The current estimate is supplied by the user; amplifier efficiency and speaker impedance are not solved. Speaker outputs are differential; do not ground either speaker output on the physical module. The lab has no audio playback.',
    12,
  ),
  model(
    'sdcard',
    'microSD SPI module',
    'Storage',
    'SPI',
    spi,
    'A 3.3 V-safe SPI SD-card breakout. Virtual capacity and fill determine occupied storage; SPI clock determines the ideal transfer ceiling. Initialization, filesystem caching, busy times, and write endurance are simplified.',
    8,
  ),
  model(
    'eeprom',
    'I²C EEPROM',
    'Storage',
    'I²C',
    i2c,
    'A serial EEPROM teaching profile. Capacity, page size, and write-cycle delay determine the sample write budget. RAM, flash, and EEPROM have different persistence and endurance characteristics.',
    2,
    0x50,
  ),
  model(
    'rtc',
    'DS3231 RTC module',
    'Storage',
    'I²C',
    i2c,
    'A battery-backed real-time clock teaching model. Clock drift and elapsed hours produce an estimated time error. The modeled coin-cell retention belongs to the external clock, not the ESP32 RTC SRAM.',
    2,
    0x68,
  ),
  model(
    'ads1115',
    'ADS1115 external ADC',
    'Instrumentation',
    'I²C',
    i2c,
    'A 16-bit external ADC with programmable full-scale range. Input voltage and range determine a signed conversion code. Selecting a larger gain range does not permit an input beyond the supply rails. This profile models one single-ended channel.',
    3,
    0x48,
  ),
  model(
    'ina219',
    'INA219 power monitor',
    'Instrumentation',
    'I²C',
    i2c,
    'A shunt current monitor teaching model. Load voltage, shunt resistance, and current determine bus power and shunt drop. Measured load terminals are internal test nodes here, not board GPIO connections.',
    3,
    0x40,
  ),
  model(
    'gps',
    'UART GNSS receiver',
    'Connectivity',
    'UART',
    uart,
    'A 3.3 V UART GNSS teaching receiver. Message length and baud rate set a synthetic serial transfer-time budget. Fix quality and satellite count are injected scenarios; no positioning is computed.',
    8,
  ),
  model(
    'rfid',
    'SPI RFID reader',
    'Connectivity',
    'SPI',
    spi,
    'An MFRC522-style teaching profile at 3.3 V. A tag-present control changes the synthetic presence event; no UID or credential is generated. Antenna tuning, RF fields, collision handling, and real credential operations are outside this model.',
    6,
  ),
  model(
    'can',
    'CAN transceiver module',
    'Connectivity',
    'TWAI',
    [vcc, ground, pin('TX'), pin('RX', 'in')],
    'A 3.3 V-compatible external CAN transceiver abstraction. Bitrate, payload length and frame rate set a utilization estimate. Physical bus termination is abstracted. GPIO cannot directly connect to CANH/CANL. Availability of TWAI varies by chip.',
    6,
  ),
  model(
    'rs485',
    'RS-485 transceiver',
    'Connectivity',
    'UART + direction',
    [vcc, ground, pin('DI', 'uart'), pin('RO', 'in'), pin('DE')],
    'A half-duplex RS-485 transceiver teaching module. Baud, payload length and turnaround delay determine its transaction estimate. Differential A/B bus lines are internal scenario connections; termination and biasing need a real bus design.',
    4,
  ),
  model(
    'displaylink',
    'Companion UART endpoint',
    'Connectivity',
    'UART',
    uart,
    'A companion UART endpoint. Cross TX and RX and share ground. The endpoint represents another controller; use System canvas to connect independent board circuits.',
    6,
  ),
];
