export type Pin = {id:string; label:string; gpio?:number; kind:'power'|'ground'|'control'|'gpio'; adc?:boolean; touch?:boolean; dac?:boolean; inputOnly?:boolean; reserved?:string; warning?:string; usb?:string};
export type Chip = {id:string; name:string; specialty:string; cpu:string; mhz:number; cores:number; sram:number; rom:number|null; rtc:number|null; gpio:number|null; wifi:string; bluetooth:string; mesh:boolean; psram:boolean; usb:string; description:string; uses:string[]; caveats:string[]; source:string; reference?:boolean; color:string; pins:Pin[]};
const range=(a:number,b:number)=>Array.from({length:b-a+1},(_,i)=>i+a);
const doc=(id:string)=>`https://documentation.espressif.com/${id.toLowerCase()}_datasheet_en.html`;
function pins(numbers:number[], opts:{adc?:number[];touch?:number[];dac?:number[];input?:number[];strap?:number[];reserved?:number[];usb?:number[]}={}):Pin[]{return [{id:'3V3',label:'3V3',kind:'power'},{id:'GND',label:'GND',kind:'ground'},{id:'EN',label:'EN',kind:'control'},...numbers.map(gpio=>({id:`GPIO${gpio}`,label:`${gpio}`,gpio,kind:'gpio' as const,adc:opts.adc?.includes(gpio),touch:opts.touch?.includes(gpio),dac:opts.dac?.includes(gpio),inputOnly:opts.input?.includes(gpio),warning:opts.strap?.includes(gpio)?'Boot strapping pin: its level at reset can change boot behavior. Keep external circuitry from forcing the wrong startup level.':undefined,reserved:opts.reserved?.includes(gpio)?'Reserved for flash / PSRAM on this teaching profile. Reusing it can stop code execution.':undefined,usb:opts.usb?.includes(gpio)?'Native USB signal. Using it as GPIO disconnects USB.':undefined})),{id:'GND2',label:'GND',kind:'ground'},{id:'5V',label:'5V',kind:'power'}]}
const referencePins=():Pin[]=>[{id:'3V3',label:'3V3',kind:'power'},{id:'GND',label:'GND',kind:'ground'},...range(0,11).map(n=>({id:`IO-${n}`,label:`IO-${n}`,kind:'gpio' as const})),{id:'5V',label:'5V',kind:'power'}];
export const chips:Chip[]=[
 {id:'ESP32',name:'ESP32',specialty:'The original all-rounder',cpu:'Xtensa LX6',mhz:240,cores:2,sram:520,rom:448,rtc:16,gpio:34,wifi:'2.4 GHz · Wi-Fi 4',bluetooth:'Classic + LE',mesh:false,psram:true,usb:'External USB-to-UART bridge',description:'The original dual-mode wireless ESP32. A versatile starting point for connected sensors, Bluetooth Classic audio, motor control, and capacitive touch.',uses:['Bluetooth Classic audio','Wi-Fi sensor nodes','Touch interfaces'],caveats:['Single-core and lower-clock part variants also exist. This profile represents a dual-core 240 MHz part.','GPIO34–39 are input-only with no internal pull-up/down. GPIO6–11 normally connect flash.','ADC2 competes with Wi-Fi. Prefer ADC1 (GPIO32–39) when Wi-Fi is active. PSRAM modules may also occupy GPIO16/17.'],source:doc('esp32'),color:'#245849',pins:pins([...range(0,19),...range(21,23),...range(25,27),...range(32,39)],{adc:[0,2,4,12,13,14,15,25,26,27,32,33,34,35,36,37,38,39],touch:[0,2,4,12,13,14,15,27,32,33],dac:[25,26],input:range(34,39),strap:[0,2,5,12,15],reserved:[6,7,8,9,10,11,16,17]})},
 {id:'ESP32-S2',name:'ESP32-S2',specialty:'USB & touch interfaces',cpu:'Xtensa LX7',mhz:240,cores:1,sram:320,rom:128,rtc:16,gpio:43,wifi:'2.4 GHz · Wi-Fi 4',bluetooth:'None',mesh:false,psram:true,usb:'USB OTG full-speed',description:'A single-core Wi-Fi MCU with native USB, touch sensing, and analog outputs. Useful for USB gadgets and connected control panels that do not need Bluetooth.',uses:['USB HID controllers','Touch control panels','Wi-Fi appliances'],caveats:['No Bluetooth radio.','External memory and module selection affect GPIO availability. USB uses GPIO19/20.'],source:doc('esp32-s2'),color:'#274d61',pins:pins([...range(0,21),...range(26,46)],{adc:range(1,20),touch:range(1,14),dac:[17,18],input:[46],strap:[0,45,46],reserved:range(26,32),usb:[19,20]})},
 {id:'ESP32-S3',name:'ESP32-S3',specialty:'AI & multimedia',cpu:'Xtensa LX7',mhz:240,cores:2,sram:512,rom:384,rtc:16,gpio:45,wifi:'2.4 GHz · Wi-Fi 4',bluetooth:'Bluetooth LE 5',mesh:false,psram:true,usb:'USB OTG + Serial/JTAG',description:'Dual cores, vector instructions, and external PSRAM support make the S3 a natural fit for camera, voice, display, and small machine-learning applications.',uses:['Camera & edge inference','Voice assistants','USB & display projects'],caveats:['Bluetooth LE only; no Bluetooth Classic. No internal DAC.','This N8R8 teaching profile reserves GPIO26–37 for memory. Actual availability depends on module suffix. GPIO19/20 carry USB.','DevKitC revisions differ in their RGB LED pin. Use the external LED experiment here.'],source:doc('esp32-s3'),color:'#20534a',pins:pins([...range(0,21),...range(26,48)],{adc:range(1,20),touch:range(1,14),input:[46],strap:[0,3,45,46],reserved:range(26,37),usb:[19,20]})},
 {id:'ESP32-S31',name:'ESP32-S31',specialty:'Connected HMI & audio',cpu:'RISC-V + LP core',mhz:320,cores:2,sram:512,rom:320,rtc:32,gpio:60,wifi:'2.4 GHz · Wi-Fi 6',bluetooth:'Classic + LE 5.4',mesh:true,psram:true,usb:'USB high-speed OTG',description:'A newer multimedia and multiprotocol family combining dual-core RISC-V, Wi-Fi 6, Bluetooth Classic/LE, and 802.15.4 with rich display and audio interfaces.',uses:['Connected HMI','LE Audio & Classic audio','Gigabit Ethernet gateways'],caveats:['Based on the preliminary v0.5 datasheet. Hardware and SDK support are evolving.','The lab exposes a conservative GPIO subset. Dedicated buses, differential ADC, and memory wiring require the exact module documentation.'],source:doc('esp32-s31'),color:'#455843',pins:pins(range(2,21))},
 {id:'ESP32-C2',name:'ESP32-C2',specialty:'Compact, cost-conscious IoT',cpu:'RISC-V',mhz:120,cores:1,sram:272,rom:576,rtc:null,gpio:14,wifi:'2.4 GHz · Wi-Fi 4',bluetooth:'Bluetooth LE 5',mesh:false,psram:false,usb:'External USB-to-UART bridge',description:'A small-footprint Wi-Fi and Bluetooth LE family for simple connected products. Lower resource budgets encourage efficient firmware and compact data structures.',uses:['Smart plugs','Simple sensors','Low-cost connectivity'],caveats:['16 KB of the SRAM is dedicated to cache; total SRAM is not free heap.','No native USB, PSRAM controller, or 802.15.4. ESP8684 is a related packaged product name.'],source:'https://www.espressif.com/en/node/5696',color:'#665437',pins:pins([...range(0,10),...range(18,20)],{adc:range(0,4),strap:[8,9]})},
 {id:'ESP32-C3',name:'ESP32-C3',specialty:'Everyday RISC-V IoT',cpu:'RISC-V',mhz:160,cores:1,sram:400,rom:384,rtc:8,gpio:22,wifi:'2.4 GHz · Wi-Fi 4',bluetooth:'Bluetooth LE 5',mesh:false,psram:false,usb:'USB Serial/JTAG only',description:'An approachable RISC-V Wi-Fi and Bluetooth LE microcontroller. Good for connected sensors and controls that fit within internal RAM.',uses:['BLE sensors','Smart lighting','Compact IoT devices'],caveats:['USB Serial/JTAG is not general USB OTG: it cannot become an arbitrary keyboard or USB host.','GPIO12–17 are reserved for memory in this profile. No PSRAM controller or internal DAC.'],source:doc('esp32-c3'),color:'#3a6159',pins:pins(range(0,21),{adc:range(0,5),strap:[2,8,9],reserved:range(12,17),usb:[18,19]})},
 {id:'ESP32-C5',name:'ESP32-C5',specialty:'Dual-band Wi-Fi 6',cpu:'RISC-V + LP core',mhz:240,cores:1,sram:384,rom:320,rtc:16,gpio:29,wifi:'2.4 + 5 GHz · Wi-Fi 6',bluetooth:'Bluetooth LE',mesh:true,psram:true,usb:'USB Serial/JTAG only',description:'Dual-band Wi-Fi 6 adds 5 GHz connectivity, while Bluetooth LE and 802.15.4 support a wide range of connected-home designs.',uses:['Dual-band IoT','Matter devices','Wireless gateways'],caveats:['5 GHz does not mean 5G cellular. Radios share resources through coexistence scheduling.','Pin exposure and flash/PSRAM use depend on the package; this lab exposes GPIO0–20 only.'],source:doc('esp32-c5'),color:'#4b526c',pins:pins(range(0,20),{adc:range(1,6),strap:[3,7],reserved:range(15,20),usb:[13,14]})},
 {id:'ESP32-C6',name:'ESP32-C6',specialty:'Wi-Fi 6 & Matter',cpu:'RISC-V + LP core',mhz:160,cores:1,sram:512,rom:320,rtc:16,gpio:30,wifi:'2.4 GHz · Wi-Fi 6',bluetooth:'Bluetooth LE',mesh:true,psram:false,usb:'USB Serial/JTAG only',description:'Wi-Fi 6, Bluetooth LE, and IEEE 802.15.4 make the C6 useful for Matter over Wi-Fi or Thread, plus Zigbee applications.',uses:['Matter & Thread','Smart-home sensors','Low-power controllers'],caveats:['No 5 GHz Wi-Fi or native PSRAM interface.','The datasheet lists 30 GPIOs for QFN40 and 22 for QFN32; exposed module pins differ.'],source:doc('esp32-c6'),color:'#335c57',pins:pins(range(0,23),{adc:range(0,6),strap:[4,5,8,9,15],usb:[12,13]})},
 {id:'ESP32-C61',name:'ESP32-C61',specialty:'Wi-Fi 6 with PSRAM',cpu:'RISC-V',mhz:160,cores:1,sram:320,rom:256,rtc:null,gpio:30,wifi:'2.4 GHz · Wi-Fi 6',bluetooth:'Bluetooth LE · Core 6.0 certified',mesh:false,psram:true,usb:'USB Serial/JTAG only',description:'A Wi-Fi 6 and Bluetooth LE family with external PSRAM support for more data-rich connected applications and connectivity adapters.',uses:['Wi-Fi adapters','Connected displays','Buffered sensor data'],caveats:['No 802.15.4 radio: Thread and Zigbee need another chip.','Bluetooth certification version is not a guarantee that every optional Bluetooth feature is implemented.'],source:doc('esp32-c61'),color:'#4f5e37',pins:pins(range(0,14),{adc:[1,3,4,5],strap:[3,4,7,8,9],usb:[12,13]})},
 {id:'ESP32-H2',name:'ESP32-H2',specialty:'Thread & Zigbee nodes',cpu:'RISC-V',mhz:96,cores:1,sram:320,rom:128,rtc:4,gpio:19,wifi:'None',bluetooth:'Bluetooth LE · 5.3 certified',mesh:true,psram:false,usb:'USB Serial/JTAG only',description:'A Bluetooth LE and 802.15.4 MCU for mesh devices. A Thread border router provides the link from its Thread network to an IP network.',uses:['Matter-over-Thread sensors','Zigbee switches','Battery-powered nodes'],caveats:['No Wi-Fi radio. Matter is an application protocol, not a separate radio.','Published GPIO count excludes internal flash connections.'],source:doc('esp32-h2'),color:'#625344',pins:pins([...range(0,5),...range(8,14),...range(22,27)],{adc:range(1,5),strap:[8,9,25],usb:[26,27]})},
 {id:'ESP32-H21',name:'ESP32-H21',specialty:'Efficient battery-powered mesh',cpu:'RISC-V',mhz:96,cores:1,sram:320,rom:128,rtc:null,gpio:null,wifi:'None',bluetooth:'Bluetooth LE',mesh:true,psram:false,usb:'Consult selected board',description:'An evolution of the H2 platform with an integrated DC-DC converter aimed at reducing active current in battery-powered Thread and Bluetooth LE devices.',uses:['Battery-powered Thread','Wireless switches','BLE sensors'],caveats:['Reference profile: numbered package pinout is not included. IO labels are virtual terminals, not physical GPIO numbers.','Power benefits depend on the complete circuit, duty cycle, and radio traffic.'],source:'https://www.espressif.com/en/news/ESP32_H21',reference:true,color:'#775b46',pins:referencePins()},
 {id:'ESP32-H4',name:'ESP32-H4',specialty:'Dual-core low-power mesh',cpu:'RISC-V with DSP',mhz:96,cores:2,sram:384,rom:128,rtc:null,gpio:null,wifi:'None',bluetooth:'Bluetooth LE 5.4',mesh:true,psram:true,usb:'Consult selected board',description:'A dual-core low-power Bluetooth LE and 802.15.4 family with DSP extensions and external memory support for more demanding mesh and wearable applications.',uses:['Advanced BLE devices','Wearables','Mesh controllers'],caveats:['Reference profile: virtual IO terminals teach protocols; they are not a board wiring diagram.','No Wi-Fi radio. Consult current datasheets for package and SDK support.'],source:'https://esp-wrover-kit.espressif.com/en/products/socs/esp32-h4',reference:true,color:'#4f616b',pins:referencePins()},
 {id:'ESP32-P4',name:'ESP32-P4',specialty:'High-performance multimedia',cpu:'RISC-V + LP core',mhz:400,cores:2,sram:768,rom:128,rtc:32,gpio:55,wifi:'None',bluetooth:'None',mesh:false,psram:true,usb:'High-speed + full-speed OTG',description:'A high-performance MCU for displays, vision, and HMI. It has MIPI CSI/DSI, image acceleration, and Ethernet, with wireless typically supplied by a companion ESP32.',uses:['High-resolution HMI','Camera processing','Ethernet devices'],caveats:['No integrated wireless radio. Development boards may add a separate C6 or other wireless chip.','768 KB describes HP L2 memory. There is also 16 KB LP ROM and 8 KB system scratchpad; silicon revisions differ.'],source:doc('esp32-p4'),color:'#324d68',pins:pins([...range(2,31),33,34,40,42,45,46,47,48],{adc:range(16,23),usb:[24,25,26,27]})},
 {id:'ESP32-E22',name:'ESP32-E22',specialty:'Tri-band connectivity coprocessor',cpu:'Dual-core RISC-V',mhz:500,cores:2,sram:1024,rom:null,rtc:null,gpio:null,wifi:'2.4 + 5 + 6 GHz · Wi-Fi 6E',bluetooth:'Classic + LE 5.4',mesh:false,psram:false,usb:'PCIe 2.1 / SDIO 3.0 host link',description:'A connectivity coprocessor designed to offload wireless work from a host system. It adds tri-band Wi-Fi 6E with 2×2 MIMO and dual-mode Bluetooth.',uses:['Host wireless adapters','High-throughput gateways','Wireless video systems'],caveats:['Reference architecture only: this is not treated as a general-purpose Arduino board. Pin wiring experiments are disabled.','Published announcement specifications do not describe free application heap; memory exercises are conceptual.'],source:'https://www.espressif.com/en/news/ESP32_E22_Announcement',reference:true,color:'#444d68',pins:[{id:'HOST',label:'HOST',kind:'control'},{id:'RF',label:'RF',kind:'control'}]},
];
export const defaultChip=chips[2];
export function describePin(pin:Pin):string{
 if(pin.id==='3V3')return 'Regulated 3.3 V supply for compatible low-current devices. It is a power rail, not a programmable output. The available current depends on the board regulator and USB source.';
 if(pin.kind==='ground')return 'Common 0 V reference. Connect the ground of every device and any external supply to this reference so logic levels have a shared meaning.';
 if(pin.id==='5V')return 'USB / board 5 V rail in this teaching carrier. Never connect 5 V directly to an ESP32 GPIO. Real boards differ in input protection and whether this rail is an input or output.';
 if(pin.kind==='control')return pin.id==='EN'?'Chip enable / reset. Pulling EN low resets the chip; it is not a general-purpose GPIO.':'Dedicated host or radio connection. Consult the reference design for electrical and interface requirements.';
 return `${pin.gpio===undefined?'Virtual learning terminal; no physical pin number is implied. ':''}${pin.inputOnly?'Digital input only. Cannot drive an LED, clock, or actuator. No internal pull resistors on the classic ESP32 input-only pins.':'Digital input or output. Use an output-capable GPIO for PWM, I²C, SPI, or UART through the GPIO matrix.'} ${pin.adc?'Includes an analog-to-digital converter channel for measuring voltage. ADC range and calibration depend on the chip and attenuation. ':''}${pin.touch?'Supports capacitive touch sensing. ':''}${pin.dac?'Includes a true analog DAC output. ':''}GPIO numbers are not physical header positions.`;
}
